name: flutter_alpha_player_plugin
description: A new Flutter plugin alphaPlayer
version: 1.0.4
homepage: https://github.com/smallwhitexujian/flutter_plugin_alpha_player.git

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_alpha_player_plugin
        pluginClass: FlutterAlphaPlayerPlugin
      ios:
        pluginClass: FlutterAlphaPlayerPlugin

